SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE (CAR_ID) IN (SELECT H.CAR_ID
                   FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
                   WHERE DATE_FORMAT(H.START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
                   GROUP BY H.CAR_ID
                   HAVING COUNT(H.CAR_ID) >= 5)
    AND DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(CAR_ID) >= 0
ORDER BY MONTH(START_DATE), CAR_ID DESC