# X: (3100 + 3100) + (500 + 200)
SELECT F.FLAVOR
FROM FIRST_HALF F JOIN JULY J ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3

# O: (3100) + (500 + 200)
SELECT F.FLAVOR
FROM FIRST_HALF F JOIN JULY J ON (F.FLAVOR = J.FLAVOR)
GROUP BY F.FLAVOR
ORDER BY F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) DESC
LIMIT 3

# O: (3100) + (500 + 200)
WITH FIRST_HALF_CNT AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
)

SELECT J.FLAVOR
FROM JULY J
GROUP BY J.FLAVOR
ORDER BY SUM(J.TOTAL_ORDER)+(SELECT F.TOTAL_ORDER FROM FIRST_HALF_CNT F WHERE F.FLAVOR = J.FLAVOR) DESC
LIMIT 3