WITH MAX_PEOPLE AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID) = (SELECT COUNT(REVIEW_ID)
                                FROM REST_REVIEW
                                GROUP BY MEMBER_ID
                                ORDER BY COUNT(REVIEW_ID) DESC
                                LIMIT 1)
)

SELECT M.MEMBER_NAME AS 'MEMBER_NAME', 
	   R.REVIEW_TEXT AS 'REVIEW_TEXT', 
	   DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON (M.MEMBER_ID = R.MEMBER_ID)
WHERE M.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_PEOPLE)
ORDER BY REVIEW_DATE, REVIEW_TEXT;