# 정답 O(최대 갯수 여러명)
WITH MAX_COUNT AS (
    SELECT COUNT(R.REVIEW_ID) AS 'MAXCNT'
    FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON (M.MEMBER_ID = R.MEMBER_ID) 
    GROUP BY M.MEMBER_ID
    ORDER BY COUNT(R.REVIEW_ID) DESC
    LIMIT 1
)

SELECT M.MEMBER_NAME AS 'MEMBER_NAME', 
	   R.REVIEW_TEXT AS 'REVIEW_TEXT', 
	   DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON (M.MEMBER_ID = R.MEMBER_ID)
WHERE (M.MEMBER_ID) IN (SELECT P.MEMBER_ID
                        FROM MEMBER_PROFILE P JOIN REST_REVIEW RV 
	                        ON (P.MEMBER_ID = RV.MEMBER_ID) 
                        GROUP BY P.MEMBER_ID
                        HAVING COUNT(RV.REVIEW_ID) 
	                        = (SELECT MAXCNT FROM MAX_COUNT)
                      )
ORDER BY REVIEW_DATE, REVIEW_TEXT;

# 정답 O(최대 갯수 여러명)
# LIMIT이 포함된 서브쿼리는 IN 지원 X(임시테이블 사용은 지원O)
WITH MAX_COUNT AS (
    SELECT COUNT(R.REVIEW_ID) AS 'MAXCNT'
    FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON (M.MEMBER_ID = R.MEMBER_ID) 
    GROUP BY M.MEMBER_ID
    ORDER BY COUNT(R.REVIEW_ID) DESC
    LIMIT 1
)

SELECT M.MEMBER_NAME AS 'MEMBER_NAME', 
	   R.REVIEW_TEXT AS 'REVIEW_TEXT', 
	   DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON (M.MEMBER_ID = R.MEMBER_ID)
WHERE (M.MEMBER_ID) IN (SELECT P.MEMBER_ID
                        FROM MEMBER_PROFILE P JOIN REST_REVIEW RV 
	                        ON (P.MEMBER_ID = RV.MEMBER_ID) 
                        GROUP BY P.MEMBER_ID
                        HAVING COUNT(RV.REVIEW_ID) 
	                        IN (SELECT MAXCNT FROM MAX_COUNT)
                      )
ORDER BY REVIEW_DATE, REVIEW_TEXT;

# 정답 O(최대 갯수 여러명)
WITH MAX_PEOPLE AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID) = (SELECT COUNT(REVIEW_ID)
                                FROM REST_REVIEW
                                GROUP BY MEMBER_ID
                                ORDER BY COUNT(REVIEW_ID) DESC
                                LIMIT 1)
)

SELECT M.MEMBER_NAME AS 'MEMBER_NAME', 
	   R.REVIEW_TEXT AS 'REVIEW_TEXT', 
	   DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON (M.MEMBER_ID = R.MEMBER_ID)
WHERE M.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_PEOPLE)
ORDER BY REVIEW_DATE, REVIEW_TEXT;

# 정답 X(최대 갯수 여러명)
# LIMIT이 포함된 서브쿼리는 IN 지원 X(임시테이블 사용은 지원O)
WITH MAX_PEOPLE AS (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(REVIEW_ID) IN (SELECT COUNT(REVIEW_ID)
                                FROM REST_REVIEW
                                GROUP BY MEMBER_ID
                                ORDER BY COUNT(REVIEW_ID) DESC
                                LIMIT 1)
)

SELECT M.MEMBER_NAME AS 'MEMBER_NAME', 
	   R.REVIEW_TEXT AS 'REVIEW_TEXT', 
	   DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS 'REVIEW_DATE'
FROM MEMBER_PROFILE M JOIN REST_REVIEW R ON (M.MEMBER_ID = R.MEMBER_ID)
WHERE M.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_PEOPLE)
ORDER BY REVIEW_DATE, REVIEW_TEXT;