SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE ID IN (
    SELECT D.ID
    FROM DEVELOPERS D JOIN SKILLCODES SA ON (D.SKILL_CODE & SA.CODE = SA.CODE AND SA.CATEGORY = 'Front End')
)
ORDER BY ID ASC;