SELECT DISTINCT C.CAR_ID AS CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C join CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON (C.CAR_ID = H.CAR_ID)
WHERE C.CAR_TYPE = '세단' AND DATE_FORMAT(START_DATE, '%m') = '10'
ORDER BY C.CAR_ID DESC