WITH TRUCK_DISCOUNT_INFO AS 
(
    SELECT P.DURATION_TYPE, P.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    WHERE P.CAR_TYPE = '트럭'
)

SELECT H.HISTORY_ID, 
    CASE
        # 트럭 90일이상 -> 할인률 얻기
        WHEN (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1) >= 90 
            THEN ROUND(C.DAILY_FEE * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1)
                       * (1 - (SELECT TDI.DISCOUNT_RATE FROM TRUCK_DISCOUNT_INFO TDI WHERE TDI.DURATION_TYPE = '90일 이상')/100)
                       , 0)
        # 트럭 30일이상 -> 할인률 얻기
        WHEN (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1) >= 30 
            THEN ROUND(C.DAILY_FEE * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1)
                        * (1 - (SELECT TDI.DISCOUNT_RATE FROM TRUCK_DISCOUNT_INFO TDI WHERE TDI.DURATION_TYPE = '30일 이상')/100)
                       , 0)
        # 트럭 7일 이상 -> 할인률 얻기
        WHEN (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1) >= 7 
            THEN ROUND(C.DAILY_FEE * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1)
                       * (1 - (SELECT TDI.DISCOUNT_RATE FROM TRUCK_DISCOUNT_INFO TDI WHERE TDI.DURATION_TYPE = '7일 이상')/100)
                       , 0)
        ELSE ROUND(C.DAILY_FEE * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1)
                   * (1)
                   , 0)
    END AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON (C.CAR_ID = H.CAR_ID)
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC