# X
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME,	A.APNT_YMD
FROM PATIENT P JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' and A.APNT_CNCL_YN = 'N'
ORDER BY A.APNT_YMD

# O
SELECT A.APNT_NO AS 'APNT_NO',
    P.PT_NAME AS 'PT_NAME', 	
    P.PT_NO AS 'PT_NO',	
    A.MCDP_CD AS 'MCDP_CD',	
    D.DR_NAME AS 'DR_NAME',	
    A.APNT_YMD AS 'APNT_YMD'
FROM APPOINTMENT A
    JOIN PATIENT P ON (A.PT_NO = P.PT_NO)
    JOIN DOCTOR D ON (A.MDDR_ID = D.DR_ID)
WHERE (DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13')
    AND A.APNT_CNCL_YN = 'N'
    AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD ASC;