WITH COUNT_TABLE AS (
    SELECT COUNT(*) AS 'ALL_CNT'
    FROM ECOLI_DATA
)

SELECT ID AS 'ID', 
    CASE
        WHEN ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY ASC) / (SELECT ALL_CNT FROM COUNT_TABLE) > 0.75 THEN 'CRITICAL'
        WHEN ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY ASC) / (SELECT ALL_CNT FROM COUNT_TABLE) > 0.50 THEN 'HIGH'
        WHEN ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY ASC) / (SELECT ALL_CNT FROM COUNT_TABLE) > 0.25 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS 'COLONY_NAME'
FROM ECOLI_DATA
ORDER BY ID ASC;