# O
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO RI JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID 
WHERE RI.ADDRESS like '서울%'
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC

# O
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO RI JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID 
GROUP BY RI.REST_ID
HAVING RI.ADDRESS like '서울%'
ORDER BY SCORE DESC, FAVORITES DESC