WITH RECURSIVE GEN_TABLE AS (
    # 초기화
    SELECT ID, 1 AS 'GEN'
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    # 재귀
    SELECT ET.ID, (GT.GEN)+1
    FROM ECOLI_DATA ET JOIN GEN_TABLE GT ON (ET.PARENT_ID = GT.ID)
)

SELECT COUNT(*) AS COUNT, GT.GEN AS 'GENERATION'
FROM GEN_TABLE GT LEFT OUTER JOIN ECOLI_DATA ET ON (GT.ID = ET.PARENT_ID)
WHERE ET.ID IS NULL 
GROUP BY GT.GEN
ORDER BY GT.GEN ASC;