WITH RECURSIVE GEN AS (
    # 초기화
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    # 재귀
    SELECT A.ID, A.PARENT_ID, (G.GENERATION+1) 
    FROM GEN G JOIN ECOLI_DATA A ON (G.ID = A.PARENT_ID)
)

SELECT COUNT(*) AS COUNT, A.GENERATION AS 'GENERATION'
FROM GEN A
WHERE A.ID NOT IN (
    SELECT B.PARENT_ID
    FROM GEN B
    WHERE B.PARENT_ID IS NOT NULL
)
GROUP BY A.GENERATION
ORDER BY A.GENERATION ASC;